spring:
  application:
    name: jiranibora
  config:
    import: optional:secrets.yaml
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

twilio:
  auth-token:
  account-sid:
  trial-number:
