server:
  port: ${PORT:8080}

spring:
  # profiles:
  #   active:
  #     - prod

  application:
    name: jiranibora

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres.ncdvodtuhpupjrltgsmt}
    password: ${DB_PASSWORD:Cnd80751xh.com}
    url: jdbc:postgresql://${DB_HOST:aws-0-eu-central-1.pooler.supabase.com}:${DB_PORT:5432}/${DB_NAME:postgres}



  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update


