
  error:
    path: /error
spring:
  application:
    name: jiranibora
  config:
    import: optional:secrets.yaml
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

twilio:
  auth-token:
  account-sid:
  trial-number:


