server:
  port: ${PORT:8080}

spring:
  # profiles:
  #   active:
  #     - prod

  application:
    name: jiranibora

  datasource:
    driver-class-name: org.postgresql.Driver
   

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
